DEBUG = False
IMG_SIZE = 512
fold = 0
MODEL_PATH = f'./log/eb04-cls-{IMG_SIZE}-f{fold}-debug/'
DATA_PATH = '/mnt/data/prostate-cancer-grade-assessment/train_512/'
num_folds = 5
seed=42
batch_size = 16
lr = 1e-4
num_epoch = 30
num_class = 6