DEBUG = False
model_type = "reg" # reg,cls,ord_reg
multi_gpu = True
tiff = False
tile_png = True
use_attention = True
apex = True
if multi_gpu:
    apex = False
IMG_SIZE = 256
num_tiles = 16
num_cluster = 6
fold = 1
backbone='regnet_800m'
pretrain_model='/home/jijianyi/workspace/kaggle/ckpt/RegNetY-800MF_dds_8gpu.pyth'
strategy='bag' #stitched,bag
fold_csv = './data/train_clean.csv'
tile_stats_csv = './data/tile_stats.csv'
DATA_PATH = f'/home/jijianyi/dataset/train_tiles/'
MODEL_PATH=f'/home/jijianyi/workspace/kaggle/logs/panda-challenge/{strategy}-{backbone}-netvlad-attention-dropout-{model_type}-{num_tiles}-{IMG_SIZE}-f{fold}/'
num_folds = 5
seed=42
batch_size = 16
lr = 3e-4
num_epoch =30
num_class = 1
accumulation_steps = 32/batch_size
BRS = False
crop_white = False
ckpt_path = None
